type WordCategory =
    | 'Fruits'
    | 'Animals'
    | 'League Of Legends'
    | 'Electronics'
    | 'Sports'
    | 'Food';

type WordBank = Record<WordCategory, string[]>;

const wordBank: WordBank = {
    Fruits: [
        'Apple',
        'Banana',
        'Orange',
        'Pear',
        'Grape',
        'Strawberry',
        'Blueberry',
        'Raspberry',
        'Blackberry',
        'Watermelon',
        'Mango',
        'Pineapple',
        'Kiwi',
        'Peach',
        'Plum',
        'Cherry',
        'Lemon',
        'Lime',
        'Coconut',
        'Avocado',
        'Pomegranate',
        'Dragonfruit',
        'Fig',
        'Guava',
        'Lychee',
        'Passionfruit',
        'Papaya',
        'Starfruit',
        'Persimmon',
        'Jackfruit',
    ],
    Animals: [
        'Dog',
        'Cat',
        'Bird',
        'Fish',
        'Snake',
        'Lizard',
        'Frog',
        'Turtle',
        'Hamster',
        'Mouse',
        'Rat',
        'Rabbit',
        'Guinea Pig',
        'Chinchilla',
        'Gerbil',
        'Parrot',
        'Horse',
        'Cow',
        'Pig',
        'Goat',
        'Sheep',
        'Chicken',
        'Duck',
        'Turkey',
        'Goose',
        'Deer',
        'Bear',
        'Lion',
        'Tiger',
        'Elephant',
    ],
    'League Of Legends': [
        // Tanks
        'Alistar',
        'Amumu',
        'Blitzcrank',
        'Galio',
        'Hecarim',
        // Fighters
        'Camille',
        'Darius',
        'Gangplank',
        'Garen',
        'Gragas',
        // Slayers
        'Akali',
        'Diana',
        'Ekko',
        'Elise',
        'Fizz',
        // Mages
        'Ahri',
        'Anivia',
        'Annie',
        'Azir',
        'Brand',
        // Marksman
        'Ashe',
        'Caitlyn',
        'Corki',
        'Draven',
        'Ezreal',
    ],
    // 30 one words electronics, no space
    Electronics: [
        'Smartphone',
        'Laptop',
        'Tablet',
        'Headphones',
        'Camera',
        'Keyboard',
        'Mouse',
        'Router',
        'Monitor',
        'Television',
        'Calculator',
        'Projector',
        'Oven',
        'Radio',
        'Drone',
        'Speaker',
        'Amplifier',
        'Refrigerator',
        'Thermostat',
        'Modem',
        'Printer',
        'Scanner',
        'Earbuds',
        'Webcam',
        'Charger',
        'Switch',
        'Receiver',
        'Console',
        'Flashdrive',
    ],
    Sports: [
        'Soccer',
        'Basketball',
        'Tennis',
        'Baseball',
        'Cricket',
        'Hockey',
        'Golf',
        'Rugby',
        'Volleyball',
        'Swimming',
        'Boxing',
        'Gymnastics',
        'Archery',
        'Badminton',
        'Cycling',
        'Running',
        'Wrestling',
        'Karate',
        'Judo',
        'Skiing',
        'Snowboarding',
        'Surfing',
        'Skating',
        'Bowling',
        'Fencing',
        'Rowing',
        'Sailing',
        'Paragliding',
        'Climbing',
        'Diving',
    ],
    Food: [
        'Pizza',
        'Sushi',
        'Burger',
        'Pasta',
        'Salad',
        'Steak',
        'Tacos',
        'Ramen',
        'Sandwich',
        'Dumplings',
        'Curry',
        'Paella',
        'Bagel',
        'Waffles',
        'Ravioli',
        'Tiramisu',
        'Falafel',
        'Crepes',
        'Tapas',
        'Kebab',
        'Tempura',
        'Pancakes',
        'Nachos',
        'Bruschetta',
        'Goulash',
        'Risotto',
        'Moussaka',
        'Poutine',
        'Biryani',
        'Stew',
    ],
};

export { wordBank };
export type { WordCategory, WordBank };
