#!/usr/bin/env node
// Generates the frontend's design tokens and icon glyphs from the Figma
// export in design/figma/, so code never restates a colour, size or path.
//
//   npm run design:tokens            write front/src/ui/generated/
//   npm run design:tokens -- --check fail if those files are out of date
//
// design:import runs this after every import. The output is generated: change
// the design in Figma, export, import.

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const repo = path.resolve(
  path.dirname(fileURLToPath(import.meta.url)),
  '../..',
);
const design = path.join(repo, 'design', 'figma');
const outDir = path.join(repo, 'front', 'src', 'ui', 'generated');
const NOTICE =
  'Generated by tools/design-tokens from design/figma. Do not edit.';

const read = (file) =>
  JSON.parse(fs.readFileSync(path.join(design, file), 'utf8'));

// Only the Paper Pop collection is the product; Club Circuit and Pocket
// Studio are archived explorations.
const UI_COLLECTION = 'Zumpo · UI';
const ARCHIVED_STYLE = /^Zumpo\/(Club Circuit|Pocket Studio)\//;

const FONT_STACKS = {
  'Nunito Sans': "'Nunito Sans', ui-rounded, system-ui, sans-serif",
  'DM Sans': "'DM Sans', system-ui, sans-serif",
};
const WEIGHTS = { Regular: 400, Medium: 500, Bold: 700, Black: 900 };

function cssName(variable) {
  const web = variable.codeSyntax?.WEB?.match(/^var\((--[\w-]+)\)$/);
  if (web) return web[1];
  return `--zumpo-${variable.name.replace(/^color\//, '').replaceAll('/', '-')}`;
}

function slug(name) {
  return name
    .replace(/^Zumpo\//, '')
    .toLowerCase()
    .replaceAll(/[^a-z0-9]+/g, '-');
}

function lowerHex(value) {
  return value.toLowerCase();
}

function tokensCss() {
  const { collections } = read('tokens/variables.json');
  const ui = collections.find((c) => c.name === UI_COLLECTION);
  if (!ui) throw new Error(`No "${UI_COLLECTION}" variable collection`);

  const lines = [];
  for (const variable of ui.variables) {
    const value = variable.resolved ?? variable.value;
    if (variable.type === 'color') {
      lines.push(`  ${cssName(variable)}: ${lowerHex(value)};`);
    } else if (variable.type === 'float') {
      lines.push(`  ${cssName(variable)}: ${value}px;`);
    } else {
      throw new Error(`Unhandled variable type ${variable.type}`);
    }
  }

  lines.push('');
  for (const [family, stack] of Object.entries(FONT_STACKS)) {
    lines.push(`  --zumpo-font-${slug(family)}: ${stack};`);
  }

  for (const style of read('tokens/text-styles.json')) {
    if (ARCHIVED_STYLE.test(style.name)) continue;
    const weight = WEIGHTS[style.style];
    if (!weight) throw new Error(`Unknown font style ${style.font}`);
    if (!FONT_STACKS[style.family]) {
      throw new Error(`Unknown font family ${style.family}`);
    }
    const name = `--zumpo-text-${slug(style.name)}`;
    lines.push('');
    if (style.description) lines.push(`  /* ${style.description} */`);
    lines.push(
      `  ${name}: ${weight} ${style.size}px / ${style.lineHeight} var(--zumpo-font-${slug(style.family)});`,
    );
    // CSS letter-spacing in em matches Figma's percent of the font size.
    let tracking = 'normal';
    if (style.letterSpacing?.endsWith('%')) {
      tracking = `${Number.parseFloat(style.letterSpacing) / 100}em`;
    } else if (style.letterSpacing) {
      tracking = style.letterSpacing;
    }
    lines.push(`  ${name}-tracking: ${tracking};`);
    lines.push(`  ${name}-line: ${style.lineHeight};`);
  }

  for (const style of read('tokens/effect-styles.json')) {
    if (ARCHIVED_STYLE.test(style.name)) continue;
    const shadows = style.effects.map((effect) => {
      const [x, y] = effect.offset;
      const inset = effect.type === 'inner_shadow' ? 'inset ' : '';
      const spread = effect.spread ? ` ${effect.spread}px` : '';
      return `${inset}${x}px ${y}px ${effect.radius}px${spread} ${lowerHex(effect.color)}`;
    });
    lines.push('');
    lines.push(`  --zumpo-shadow-${slug(style.name)}: ${shadows.join(', ')};`);
  }

  return `/* ${NOTICE} */\n\n:root {\n${lines.join('\n').replaceAll(/\n{3,}/g, '\n\n')}\n}\n`;
}

const round = (n) => Math.round(n * 1000) / 1000;

// Each glyph is a 24 × 24 component of stroked vectors. The export writes
// every vector as its own SVG, padded by half the stroke on each side, so
// each path is shifted back to where it sits in the component.
function glyphsTs() {
  const icon = read('components/icon.json');
  const glyphs = {};
  for (const variant of icon.variants) {
    const name = variant.props.Glyph;
    const { node } = variant;
    if (node.w !== 24 || node.h !== 24) {
      throw new Error(`Glyph ${name} is ${node.w} × ${node.h}, not 24 × 24`);
    }
    glyphs[name] = node.children.map((child) => {
      if (child.type !== 'VECTOR' || !child.svg) {
        throw new Error(`Glyph ${name} has a ${child.type} child`);
      }
      const svg = fs.readFileSync(path.join(design, child.svg), 'utf8');
      const width = Number(svg.match(/<svg[^>]* width="([\d.]+)"/)[1]);
      const height = Number(svg.match(/<svg[^>]* height="([\d.]+)"/)[1]);
      const paths = [...svg.matchAll(/<path ([^>]*)\/>/g)];
      if (paths.length !== 1) {
        throw new Error(`${child.svg} has ${paths.length} paths, expected 1`);
      }
      const attrs = Object.fromEntries(
        [...paths[0][1].matchAll(/([\w-]+)="([^"]*)"/g)].map((m) => [
          m[1],
          m[2],
        ]),
      );
      if (attrs['stroke-width'] !== '2') {
        throw new Error(`${child.svg} is not a 2 px stroke`);
      }
      return {
        d: attrs.d,
        x: round(child.x - (width - child.w) / 2),
        y: round(child.y - (height - child.h) / 2),
        ...(attrs.fill && attrs.fill !== 'none' ? { fill: true } : {}),
      };
    });
  }

  const body = Object.entries(glyphs)
    .map(([name, parts]) => {
      const items = parts
        .map(
          (p) =>
            `    { d: '${p.d}', x: ${p.x}, y: ${p.y}${p.fill ? ', fill: true' : ''} },`,
        )
        .join('\n');
      return `  '${name}': [\n${items}\n  ],`;
    })
    .join('\n');

  return `// ${NOTICE}

export interface GlyphPath {
  /** Path data in the vector's own box. */
  d: string;
  /** Where that box sits in the 24 × 24 glyph. */
  x: number;
  y: number;
  /** Filled as well as stroked. */
  fill?: boolean;
}

export const glyphs = {
${body}
} as const satisfies Record<string, readonly GlyphPath[]>;

export type GlyphName = keyof typeof glyphs;
`;
}

// The canvas draws with these, so it cannot read them from CSS.
function brushesTs() {
  const { collections } = read('tokens/variables.json');
  const ui = collections.find((c) => c.name === UI_COLLECTION);
  const brushes = ui.variables
    .filter((v) => v.name.startsWith('color/brush/'))
    .map(
      (v) =>
        `  { name: '${v.name.slice('color/brush/'.length)}', color: '${lowerHex(v.resolved ?? v.value)}' },`,
    );
  if (!brushes.length) throw new Error('No color/brush/* variables');
  return `// ${NOTICE}

/** The drawer's palette, in toolbar order. */
export const brushes = [
${brushes.join('\n')}
] as const;

export type BrushName = (typeof brushes)[number]['name'];
`;
}

// A colour variable bound in the export, as the token that carries it.
function fillOf(token) {
  const name = token.replace(/^\$Zumpo · UI:color\//, '');
  return `var(--zumpo-${name.replaceAll('/', '-')})`;
}

// The turtle sample drawing, the Draw & Guess artwork on the home and games
// pages, one entry per Stage variant. Each part is a stroked vector or a
// filled ellipse, placed as in the component.
function drawingsTs() {
  const set = read('components/sample-turtle-drawing.json');
  const stages = set.variants.map(({ props, node }) => {
    const parts = node.children.map((child) => {
      if (child.type === 'ELLIPSE') {
        return `{ ellipse: true, x: ${round(child.x)}, y: ${round(child.y)}, w: ${round(child.w)}, h: ${round(child.h)}, fill: '${fillOf(child.fills[0])}' }`;
      }
      if (child.type !== 'VECTOR' || !child.svg) {
        throw new Error(`Turtle part ${child.name} is a ${child.type}`);
      }
      const svg = fs.readFileSync(path.join(design, child.svg), 'utf8');
      const width = Number(svg.match(/<svg[^>]* width="([\d.]+)"/)[1]);
      const height = Number(svg.match(/<svg[^>]* height="([\d.]+)"/)[1]);
      const paths = [...svg.matchAll(/<path ([^>]*)\/>/g)];
      if (paths.length !== 1) {
        throw new Error(`${child.svg} has ${paths.length} paths, expected 1`);
      }
      const attrs = Object.fromEntries(
        [...paths[0][1].matchAll(/([\w-]+)="([^"]*)"/g)].map((m) => [
          m[1],
          m[2],
        ]),
      );
      return `{ d: '${attrs.d}', x: ${round(child.x - (width - child.w) / 2)}, y: ${round(child.y - (height - child.h) / 2)}, stroke: '${lowerHex(attrs.stroke)}', width: ${Number(attrs['stroke-width'])} }`;
    });
    return `  ${props.Stage}: [\n${parts.map((part) => `    ${part},`).join('\n')}\n  ],`;
  });
  const { w, h } = set.variants[0].node;
  return `// ${NOTICE}

export type DrawingPart =
  | {
      /** Path data in the vector's own box, at (x, y) in the drawing. */
      d: string;
      x: number;
      y: number;
      stroke: string;
      width: number;
    }
  | { ellipse: true; x: number; y: number; w: number; h: number; fill: string };

/** The sample drawing's box, in canvas pixels. */
export const TURTLE_SIZE = { width: ${w}, height: ${h} } as const;

/** Sample / Turtle drawing, stage by stage. */
export const turtle = {
${stages.join('\n')}
} as const satisfies Record<string, readonly DrawingPart[]>;
`;
}

// Exports made before the exporter kept arc data read every ellipse as a
// disc. Until the next export carries it, these are the arcs Figma draws,
// measured from its preview; an export that has arc data wins.
const ARCS_BEFORE_EXPORT = {
  Ring: { start: 0, end: 360, inner: 0.5 },
  Half: { start: 180, end: 360, inner: 0 },
};

const n = (value) => String(round(value));

// An ellipse in its own w × h box as path data: a disc, a ring, or a slice
// from `start` to `end` degrees, clockwise from three o'clock as in Figma.
function ellipsePath(w, h, arc) {
  const rx = w / 2;
  const ry = h / 2;
  const disc = (scale) =>
    `M${n(rx)} ${n(ry - ry * scale)}` +
    `A${n(rx * scale)} ${n(ry * scale)} 0 1 1 ${n(rx)} ${n(ry + ry * scale)}` +
    `A${n(rx * scale)} ${n(ry * scale)} 0 1 1 ${n(rx)} ${n(ry - ry * scale)}Z`;
  if (!arc) return disc(1);
  const whole = Math.abs(arc.end - arc.start - 360) < 1e-6;
  if (whole) return arc.inner ? disc(1) + disc(arc.inner) : disc(1);
  if (arc.inner) throw new Error('A slice of a ring is not supported');
  const at = (degrees) => {
    const radians = (degrees * Math.PI) / 180;
    return `${n(rx + rx * Math.cos(radians))} ${n(ry + ry * Math.sin(radians))}`;
  };
  const large = arc.end - arc.start > 180 ? 1 : 0;
  return `M${n(rx)} ${n(ry)}L${at(arc.start)}A${n(rx)} ${n(ry)} 0 ${large} 1 ${at(arc.end)}Z`;
}

function roundedRectPath(w, h, r) {
  return (
    `M${n(r)} 0H${n(w - r)}A${n(r)} ${n(r)} 0 0 1 ${n(w)} ${n(r)}` +
    `V${n(h - r)}A${n(r)} ${n(r)} 0 0 1 ${n(w - r)} ${n(h)}` +
    `H${n(r)}A${n(r)} ${n(r)} 0 0 1 0 ${n(h - r)}` +
    `V${n(r)}A${n(r)} ${n(r)} 0 0 1 ${n(r)} 0Z`
  );
}

// The Pairs card faces: one filled shape per Symbol variant, as path data
// placed in the symbol's box, and the brush token that fills it.
function pairsSymbolsTs() {
  const set = read('components/pairs-symbol.json');
  const { collections } = read('tokens/variables.json');
  const ui = collections.find((c) => c.name === UI_COLLECTION);
  // A polygon or star exports as an SVG with its colour inlined; it is one
  // of the brushes.
  const brushOf = (hex) => {
    const brush = ui.variables.find(
      (v) =>
        v.name.startsWith('color/brush/') &&
        lowerHex(v.resolved ?? '') === lowerHex(hex),
    );
    if (!brush) throw new Error(`${hex} is not a brush colour`);
    return `var(${cssName(brush)})`;
  };

  const symbols = set.variants.map(({ props, node }) => {
    const name = props.Symbol;
    if (node.children.length !== 1) {
      throw new Error(`Symbol ${name} has ${node.children.length} shapes`);
    }
    const [shape] = node.children;
    const placed = (d, fill, x = shape.x, y = shape.y) =>
      `  { name: '${name}', d: '${d}', x: ${n(x)}, y: ${n(y)}, fill: '${fill}' },`;
    if (shape.type === 'ELLIPSE') {
      const arc = shape.arc ?? ARCS_BEFORE_EXPORT[name.split(' ')[0]];
      return placed(ellipsePath(shape.w, shape.h, arc), fillOf(shape.fills[0]));
    }
    if (shape.type === 'RECTANGLE') {
      return placed(
        roundedRectPath(shape.w, shape.h, shape.radius ?? 0),
        fillOf(shape.fills[0]),
      );
    }
    if (!shape.svg) throw new Error(`Symbol ${name} is a ${shape.type}`);
    const svg = fs.readFileSync(path.join(design, shape.svg), 'utf8');
    const paths = [...svg.matchAll(/<path ([^>]*)\/>/g)];
    if (paths.length !== 1) {
      throw new Error(`${shape.svg} has ${paths.length} paths, expected 1`);
    }
    const attrs = Object.fromEntries(
      [...paths[0][1].matchAll(/([\w-]+)="([^"]*)"/g)].map((m) => [m[1], m[2]]),
    );
    // Figma centres a polygon or star across its box and stands its first
    // point on the top edge. The export crops to the points, rounding the
    // crop out to whole pixels, so the points themselves say where they lie.
    const xs = [...attrs.d.matchAll(/[ML](-?[\d.]+) |H(-?[\d.]+)/g)].map((m) =>
      Number(m[1] ?? m[2]),
    );
    const left = Math.min(...xs);
    const right = Math.max(...xs);
    if (/[^MLHVZ\d.\s-]/.test(attrs.d)) {
      throw new Error(`${shape.svg} is not made of straight lines`);
    }
    return placed(
      attrs.d,
      brushOf(attrs.fill),
      shape.x + (shape.w - (right - left)) / 2 - left,
      shape.y,
    );
  });
  const { w } = set.variants[0].node;
  return `// ${NOTICE}

export interface PairsSymbolShape {
  name: string;
  /** Path data, filled even-odd, placed at (x, y) in the symbol's box. */
  d: string;
  x: number;
  y: number;
  fill: string;
}

/** A symbol's square box, in pixels at its design size. */
export const PAIRS_SYMBOL_SIZE = ${w};

/** Zumpo/Pairs symbol, in variant order: what a deck of pairs is dealt from. */
export const pairsSymbols = [
${symbols.join('\n')}
] as const satisfies readonly PairsSymbolShape[];
`;
}

const outputs = {
  'tokens.css': tokensCss(),
  'glyphs.ts': glyphsTs(),
  'brushes.ts': brushesTs(),
  'drawings.ts': drawingsTs(),
  'pairs-symbols.ts': pairsSymbolsTs(),
};

const check = process.argv.includes('--check');
let stale = false;
fs.mkdirSync(outDir, { recursive: true });
for (const [file, content] of Object.entries(outputs)) {
  const target = path.join(outDir, file);
  const current = fs.existsSync(target)
    ? fs.readFileSync(target, 'utf8')
    : null;
  if (current === content) continue;
  if (check) {
    console.error(
      `${path.relative(repo, target)} is out of date: run npm run design:tokens`,
    );
    stale = true;
  } else {
    fs.writeFileSync(target, content);
    console.log(`Wrote ${path.relative(repo, target)}`);
  }
}
if (stale) process.exit(1);
